[package]
name = "vcddiff"
version = "0.1.0"
edition = "2021"

[dependencies]
wellen = "0.9.14"
indexmap = "2.9.0"
indicatif = "0.17.11"
itertools = "0.14.0"
clap = { version = "4.5.30", features = ["derive"] }
